### ISSUE TITLE
Anode resistor

### ISSUE THREAD

**Issue by jetty840** [radhoo/uradmonitor_kit1#10]
Recommended anode resistor for the SBM-20 in the datasheet is 5.1MOhm, however this design has 10M Ohm and most other designs using this tube use a closer value (4.7MOhm).

What would be the effect on detection rate by changing it to closer to the recommended value?  Any other issues?

**Comment by radhoo** [comment]
Geiger tube theory paperwork documents the process of selecting the anode resistor beyond the simple datasheet recommendation. The idea is that with an increased resistor, the tube life if prolonged. What is important is to keep the ratio between the anode resistor and the cathode resistor, in order to set the desired amplitude of the output pulse. This has been carefully chosen for the KIT1, but also the other uRADMonitor detectors.

Here is a copy: http://www.rsp-italy.it/Electronics/Databooks/Sensors/_contents/Centronic%20-%20Geiger%20Tube%20Theory%20-%20ISS1.pdf
